<div class="row">
    <div class="col-sm">
    </div>
    <div class="col-sm">
    <form name="formUser" action="" method="post" enctype="multipart/form-data">
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Activity Name</label>
          <div class="col-sm-10">
            <input class="form-control" id="act_name" name="act_name" value="" required="" type="text">
            <div class="invalid-feedback">
              Please fill data.
            </div>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Date</label>
          <div class="col-sm-10">
            <input class="form-control" id="act_date" name="act_date" required="" type="date">
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm">Detail</label>
          <div class="col-sm-10">
            <textarea class="form-control" id="act_detail" name="act_detail" required="" type="text"></textarea>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-2 col-form-label col-form-label-sm"></label>
          <div class="col-sm-10">
            <div class="custom-file">

              <div class="input-group">
                  <span class="input-group-btn">
                      <span class="btn btn-default btn-file">
                          Browse… <input type="file" id="act_picture" name="act_picture">
                    </span>
                  </span>
              </div>

              <!--<input type="file" class="form-control custom-file-input" name="act_picture" id="act_picture">
              <label class="custom-file-label" for="customFile" >Choose picture</label>
              <input type="file" name="act_picture"  class="custom-file-input"  >
              <label class="custom-file-label">Choose file</label>-->
            </div>
          </div>
        </div>
        <div class="form-group">
          <label class="col col-form-label col-form-label-sm"></label>
          <input class="btn btn-sm btn-success" type="submit" value="Submit">
          <label class="col col-form-label col-form-label-sm"></label>
          <label class="col col-form-label col-form-label-sm"></label>
          <label class="col col-form-label col-form-label-sm"></label>
        </div>
      </form>
      </div>
      <div class="col-sm">
    </div>
 </div>
