<div class="row">
    <div class="col-sm">
    </div>
    <div class="table-responsive">
    <h3 class="text-center">ACTIVITIES.</h3>
    <table class="table table-striped table-light" style="color:gray;">

              <thead>
                <tr style="color:black;">
                  <th scope="col">No.</th>
                  <th scope="col">Activity</th>
                  <th scope="col">Date</th>
                  <th scope="col"></th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
              <?php
              $id=$this->session->get('memberAuthen');
              $act = Activities::find("id = '$id'");
              for ($i=0;$i<count($act);$i++){?>
                <tr>
                  <th scope="row"><h6><?php echo "$i"+1 ?></h6></th>
                  <td>
                     <h6><?php echo $act[$i]->act_name; ?></h6>
                    <img class="img-thumbnail" style="width:auto; height:150px;" src="<?php echo $this->url->getBaseUri().'public/img/'.$act[$i]->act_picture; ?>">
                  </td>
                  <td><h6><?php echo $act[$i]->act_date; ?></h6></td>
                  <td><a style="color:white;" href="<?php echo $this->url->getBaseUri(); ?>event/setId/<?php echo $act[$i]->act_num;?>" class="btn btn-info" id="edit<?php echo $act[$i]->act_num;?>" name="edit<?php echo $act[$i]->act_num;?>" value="<?php echo $act[$i]->act_num;?>">edit</a></td>
                  <td><a href="<?php echo $this->url->getBaseUri(); ?>event/deleteId/<?php echo $act[$i]->act_num;?>" class="btn btn-danger">delete</a></td>
                </tr>
              <?php }?>
              </tbody>
            </table>
          </div>
    </div>
    <div class="col-sm">
    </div>
  </div>
  <div class="container">
  <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
  <a href="<?php echo $this->url->getBaseUri(); ?>event/add" class="btn btn-success">ADD</a>
</div>
